repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v5.0.0'
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-yaml

  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
    - id: flake8
      args: ["--config=.flake8"]

  - repo: local
    hooks:
      - id: update-backend-requirements
        name: Check if AnalyticQ backend dependencies are updated
        entry: python scripts/update_backend_requirements.py
        language: python
        always_run: true
        pass_filenames: false
