services:

  rabbitmq-broker:
      image: rabbitmq:${RABBITMQ_VERSION}-management
      container_name: rabbitmq-broker
      restart: always
      env_file: .env
      ports:
        - "${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}"
        - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
      environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      networks:
        - analyticq-network

  postgres:

    image: postgres:${POSTGRES_VERSION}
    container_name: analyticq-db-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"  # Mapping PostgreSQL port to local machine
    networks:
      - analyticq-network
    entrypoint: >
      bash -c "
        docker-entrypoint.sh postgres &
        sleep 10 &&
        until pg_isready -h localhost -U ${POSTGRES_ROOT_USER}; do
          sleep 2;
        done;
        psql -U ${POSTGRES_ROOT_USER} -d ${POSTGRES_DB} -c \"CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';\"
        psql -U ${POSTGRES_ROOT_USER} -d ${POSTGRES_DB} -c \"GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};\"
        wait
      "

  analyticq-frontend:
    build:
      context: ./analyticq-frontend
      dockerfile: Dockerfile
    container_name: analyticq-frontend
    restart: always
    ports:
      - "8080:5173"
    env_file:
     - .env
    depends_on:
      - postgres
      - analyticq-backend
    networks:
      - analyticq-network

  analyticq-backend:
    build:
      context: ./analyticq-backend
      dockerfile: Dockerfile
    container_name: analyticq-backend
    env_file: .env
    environment:
      - RUNNING_IN_DOCKER=true
      - ANALYTICQ_TMP_BASE=/analyticq-data
    ports:
      - "8000:8000"
    restart: always
    depends_on:
    - postgres
    volumes:
      # Mount Docker socket for pulling images
      - /var/run/docker.sock:/var/run/docker.sock
      - analyticq-data:/analyticq-data
    group_add:
      - ${DOCKER_GID:-0}
    networks:
      - analyticq-network

volumes:
  rabbitmq_data:
    name: rabbitmq_data
  postgres_data:
    name: postgres_data
  analyticq-data:
    name: analyticq-data

networks:
  analyticq-network:
    driver: bridge
