import pytest
from analyticq.engine.core.models import AnalyticQSASTScanResult
from analyticq.engine.tools.php import PHPStanTool
from analyticq.exception import (ScanConfigurationException,
                                 ScanTimeoutException)


@pytest.fixture(scope="module")
def phpstan_tool():
    "Initialize and configure StaticcheckTool with test settings."""
    tool = PHPStanTool()
    # Reduce timeout for test environment
    return tool


@pytest.fixture(scope="module")
def sample_code(tmp_path_factory):
    """Create a temporary PHP file with known PHPStan violations."""
    code_dir = tmp_path_factory.mktemp("code")
    test_file = code_dir / "test_sample.php"

    # Create a sample PHP file with known PHPStan issues
    # Code sample generated by AI for test purposes
    test_code = """<?php
declare(strict_types=1);

namespace App\Tests;

class User {
    private string $name;
    private ?int $age = null;

    // PHPStan: Property is never read
    private $unusedProperty;

    // PHPStan: Missing type declaration
    private $status;

    public function setName($name) {
        // PHPStan: Parameter $name has no type specified
        $this->name = $name;
    }

    public function getName(): string {
        // PHPStan: Accessing undefined property
        return $this->firstname;
    }

    public function setAge(?int $age): void {
        $this->age = $age;
    }

    public function getAge(): int {
        // PHPStan: Method returns int but can return null
        return $this->age;
    }

    public function processData(?array $data): string {
        // PHPStan: Possibly null array access
        return $data['key'];
    }

    public function divide(int $a, int $b): float {
        // PHPStan: Dividing by possibly zero value
        return $a / $b;
    }
}

class Calculator {
    public function add($a, $b) {
        // PHPStan: Operation on mixed types
        return $a + $b;
    }

    public function process(array $items): void {
        // PHPStan: Foreach on possibly empty array
        foreach ($items as $item) {
            echo $item;
        }
    }
}

function testFunction(): void {
    // PHPStan: Class instantiation without constructor params
    $user = new Unknown();

    // PHPStan: Call to undefined method
    $user->undefinedMethod();

    // PHPStan: Variable might not be defined
    echo $undefinedVariable;

    // PHPStan: Unreachable code
    return;
    echo "This will never execute";
}

class TypeHints {
    /** @var array */
    private $items;

    public function __construct() {
        // PHPStan: Array shape mismatch
        $this->items = [
            'key' => ['nested' => 'value']
        ];
    }

    public function getItem(string $key): string {
        // PHPStan: Array access on possibly null value
        return $this->items[$key];
    }
}

interface PaymentProcessor {
    public function process(float $amount): void;
}

class PaymentHandler {
    private PaymentProcessor $processor;

    // PHPStan: Missing required constructor parameter
    public function __construct() {
    }

    public function handlePayment(float $amount): void {
        // PHPStan: Accessing uninitialized property
        $this->processor->process($amount);
    }
}

trait BadTrait {
    // PHPStan: Trait method should be abstract
    private function abstractMethod() {
    }
}

abstract class AbstractClass {
    // PHPStan: Abstract method implementation missing
    abstract public function requiredMethod();

    public function checkCondition(bool $condition): string {
        if ($condition) {
            return "True";
        }
        // PHPStan: Missing return statement
    }
}

// PHPStan: Class implements interface but misses some methods
class BrokenImplementation implements PaymentProcessor {
}
"""  # noqa
    test_file.write_text(test_code)
    return code_dir


@pytest.mark.integration
@pytest.mark.asyncio
async def test_full_php_analysis(sample_code, phpstan_tool):
    """Test full PHPStan analysis workflow from code scan to report generation."""
    try:
        # 1. Install the container image
        await phpstan_tool.install()

        # 2. Run analysis on sample code
        result = await phpstan_tool.run_scan(
            codebase_path=str(sample_code),
        )

        assert isinstance(result, AnalyticQSASTScanResult)
        assert result.metadata["tool_name"] == "PHPStan"
        assert len(result.issues) > 0

        assert "metrics" in result.metadata
        assert "total_files_analyzed" in result.metadata
        assert result.metadata["total_files_analyzed"] == 1
        assert result.metadata["metrics"]["file_errors"] > 0

        for issue in result.issues:
            assert issue.path.endswith("test_sample.php")

        error_categories = {issue.metadata.get("identifier", "").split(".")[0]
                            for issue in result.issues}
        expected_categories = {"property", "missingType", "return", "class", "method"}

        assert expected_categories.issubset(error_categories), "Missing expected error categories"

        assert "tool_specific" in result.metadata
        assert "errors" in result.metadata["tool_specific"]

    except ScanConfigurationException as e:
        pytest.fail(f"Configuration error: {str(e)}")
    except ScanTimeoutException as e:
        pytest.fail(f"Analysis timed out: {str(e)}")
    except Exception as e:
        pytest.fail(f"Unexpected error: {str(e)}")
