import pytest
from analyticq.engine.core.models import (AnalyticQSASTIssueModel,
                                          AnalyticQSASTScanResultModel)
from analyticq.engine.tools import RubocopTool
from analyticq.exception import (ScanConfigurationException,
                                 ScanTimeoutException)


@pytest.fixture(scope="module")
def rubocop_tool():
    "Initialize and configure StaticcheckTool with test settings."""
    tool = RubocopTool()
    # Reduce timeout for test environment
    return tool


@pytest.fixture(scope="module")
def sample_code(tmp_path_factory):
    """Create a temporary C++ file with known Cppcheck violations."""
    code_dir = tmp_path_factory.mktemp("code")
    test_file = code_dir / "test_sample.rb"
    # Code sample generated by AI for test purposes
    test_code = """
# Style/LineLength: Line is too long
def bad_method(parameter_one, parameter_two, parameter_three, parameter_four, parameter_five, parameter_six, parameter_seven)
  # Naming/VariableName: Use snake_case for variable names
  someVariable = parameter_one + 1

  # Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression
  if parameter_one > 0
    # Style/StringLiterals: Prefer single-quoted strings
    puts "Parameter is positive"
    return someVariable
  else
    # Lint/UselessAssignment: Useless assignment to variable
    unused = 42
    return parameter_one
  end
end

# Metrics/MethodLength: Method is too long
# Metrics/AbcSize: ABC size is too high
def another_bad_method
  array = [1, 2, 3, 4, 5]

  # Style/For: Prefer each over for
  for item in array
    puts item
  end

  # Style/RedundantReturn: Redundant return statement
  return true
end
    """
    test_file.write_text(test_code)
    return code_dir


@pytest.mark.integration
@pytest.mark.asyncio
async def test_full_analysis(rubocop_tool, sample_code):
    try:
        await rubocop_tool.install()

        # 2. Run analysis on sample code
        results = await rubocop_tool.run_scan(
            codebase_path=str(sample_code),
        )
        print(results)

        # 3. Validate results structure
        assert isinstance(results, AnalyticQSASTScanResultModel), "Invalid results type"
        assert len(results.issues) >= 7, "Should find at least 7 issues"

        assert "tool_name" in results.scan_metadata
        assert "metrics" in results.scan_metadata
        assert results.scan_metadata["tool_name"] == "rubocop"

        for issue in results.issues:
            assert isinstance(issue, AnalyticQSASTIssueModel)
            assert issue.path.endswith("test_sample.rb")

    except ScanConfigurationException as e:
        pytest.fail(f"Configuration error: {str(e)}")
    except ScanTimeoutException as e:
        pytest.fail(f"Analysis timed out: {str(e)}")
    except Exception as e:
        pytest.fail(f"Unexpected error: {str(e)}")
