import hashlib
import json
from datetime import datetime
from threading import Lock
from typing import Dict, Union

from analyticq.engine import AnalyticQScanContext


class AnalyticQIDGeneratorService:

    _instance = None
    _lock = Lock()

    def __new__(cls, *args, **kwargs):
        with cls._lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self, prefix: str = "S"):
        if not hasattr(self, "initialized"):
            self.prefix = prefix
            self.initialized = True

    def generate_codebase_id(self, scan_context: AnalyticQScanContext) -> str:
        """
        Generates a unique identifier for a codebase based on scan context information.

        The ID is generated by combining path and repository information from the scan context
        and creating a SHA-256 hash of the combined string. The final ID is truncated to 12 characters.

        Args:
            scan_context (AnalyticQScanContext): Object containing scan context information including
                path and repository name.

        Returns:
            str: A 12-character hexadecimal string representing the unique codebase ID.

        Raises:
            ValueError: If insufficient context information is available to generate an ID.

        Example:
            scan_ctx = AnalyticQScanContext(path='/path/to/repo', repo_name='my-repo')
            id_gen = IdGeneratorService()
            codebase_id = id_gen.generate_codebase_id(scan_ctx)  # Returns something like 'a1b2c3d4e5f6'
        """
        components = []

        # Add path information
        if hasattr(scan_context, 'path') and scan_context.path:
            # Use last two path components for stability while maintaining uniqueness
            path_parts = scan_context.path.split('/')[-2:]
            components.extend(part.lower() for part in path_parts if part)

        if hasattr(scan_context, 'repo_name') and scan_context.repo_name:
            components.append(scan_context.repo_name.lower())

        if not components:
            raise ValueError("Unable to generate codebase ID: insufficient context")

        content = '|'.join(components)
        return hashlib.sha256(content.encode()).hexdigest()[:12]

    def generate_scan_id(self, scan_context: AnalyticQScanContext) -> str:
        """Generate a unique scan ID for an AnalyticQ scan.
        The scan ID is composed of four parts separated by hyphens:
        1. A prefix (defined in the class)
        2. A codebase ID (generated from the scan context)
        3. A source ID (either first 7 chars of git commit hash or generated hash)
        4. A timestamp in YYYYMMDDhhmmss format
        Args:
            scan_context (AnalyticQScanContext): Context object containing scan information
                including codebase location and optionally git commit hash
        Returns:
            str: A unique scan ID in the format "prefix-codebase_id-source_id-timestamp"
        Example:
            >>> generator.generate_scan_id(scan_context)
            'AQ-abc123-de45678-20231215143022'
        """

        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        codebase_id = self.generate_codebase_id(scan_context)
        if hasattr(scan_context, 'last_commit_hash') and scan_context.last_commit_hash:
            source_id = scan_context.last_commit_hash[:7]
        else:
            # For non-git sources, generate a hash based on timestamp and location
            source_hash = hashlib.sha256(f"{timestamp}|{codebase_id}".encode()).hexdigest()
            source_id = source_hash[:7]

        return f"{self.prefix}-{codebase_id}-{source_id}-{timestamp}"

    def generate_issue_id(self, scan_id, issue_content: Union[Dict, str]) -> str:
        """
        Generates a unique issue ID by combining a scan ID with a hash of the issue content.

        Args:
            scan_id: The ID of the scan associated with the findinf
            issue_content (str): The content of the issue to be hashed

        Returns:
            str: A unique finding ID in the format "scan_id-issue_hash" where issue_hash
                 is an 8-character hexadecimal hash of the issue content

        Example:
            >>> generate_issue_id("scan123", "Critical security vulnerability found")
            'scan123-a1b2c3d4'
        """
        if isinstance(issue_content, dict):
            issue_content = json.dumps(issue_content)

        issue_hash = hashlib.sha256(issue_content.encode()).hexdigest()[:8]
        return f"{scan_id}-{issue_hash}"

    def parse_scan_id(self, scan_id: str) -> dict:
        """
        Parses a scan ID into its component parts.

        Args:
            scan_id (str): The scan ID to parse in format '{prefix}-{codebase_id}-{source_id}-{timestamp}'

        Returns:
            dict: A dictionary containing the parsed components:
                - prefix: The scan prefix
                - codebase_id: The codebase identifier
                - source_id: The source identifier
                - timestamp: The parsed datetime object

        Raises:
            ValueError: If the scan ID format is invalid or parsing fails
        """
        try:
            id_parts = scan_id.split("-")
            if len(id_parts) != 4:
                raise ValueError("Invalid scan ID format")

            timestamp = datetime.strptime(id_parts[3], "%Y%m%d%H%M%S")

            return {
                "prefix": id_parts[0],
                "codebase_id": id_parts[1],
                "source_id": id_parts[2],
                "timestamp": timestamp
            }
        except ValueError as e:
            raise ValueError(f"Invalid scan ID format: {str(e)}")
        except Exception as e:
            raise ValueError(f"Error parsing scan ID: {str(e)}")
