[tox]
envlist = py313

[testenv]
deps =
    pytest
    coverage
    -r requirements.txt
commands =
    coverage run -m pytest
    coverage report
    coverage html
allowlist_externals =
    coverage # Allow coverage to be run as an external command
[pytest]
addopts = --maxfail=1 --disable-warnings -v
