from unittest.mock import patch

import pytest
from analyticq.engine.core.models import AnalyticQConfidence, AnalyticQSeverity
from analyticq.engine.parser import SpotBugsParser
from analyticq.exception import ScanParserException


@pytest.fixture
def sample_sarif_data() -> dict:
    """Create sample SARIF data for testing."""
    # Sample responde generated by AI tool
    return {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "SpotBugs",
                        "version": "4.7.3",
                        "rules": [
                            {
                                "id": "EI_EXPOSE_REP",
                                "shortDescription": {
                                    "text": "May expose internal representation by returning reference to mutable object"
                                },
                                "helpUri": "https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html#EI_EXPOSE_REP",
                                "properties": {
                                    "tags": ["security", "vulnerability"]
                                }
                            },
                            {
                                "id": "DLS_DEAD_LOCAL_STORE",
                                "shortDescription": {
                                    "text": "Dead store to local variable"
                                },
                                "helpUri": "https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html#DLS_DEAD_LOCAL_STORE"
                            }
                        ]
                    }
                },
                "results": [
                    {
                        "ruleId": "EI_EXPOSE_REP",
                        "level": "error",
                        "message": {
                            "text": "This method returns a reference to an array that may be mutable",
                            "arguments": ["getData()"]
                        },
                        "locations": [
                            {
                                "physicalLocation": {
                                    "artifactLocation": {
                                        "uri": "src/main/java/com/example/Data.java"
                                    },
                                    "region": {
                                        "startLine": 25,
                                        "endLine": 27
                                    }
                                }
                            }
                        ]
                    },
                    {
                        "ruleId": "DLS_DEAD_LOCAL_STORE",
                        "level": "warning",
                        "message": {
                            "text": "Value assigned to variable 'result' is never used"
                        },
                        "locations": [
                            {
                                "physicalLocation": {
                                    "artifactLocation": {
                                        "uri": "src/main/java/com/example/Processor.java"
                                    },
                                    "region": {
                                        "startLine": 42,
                                        "endLine": 42
                                    }
                                }
                            }
                        ]
                    }
                ]
            }
        ]
    }


@pytest.fixture
def spotbug_parser() -> SpotBugsParser:
    return SpotBugsParser()


def test_severity_mapping(spotbug_parser):
    """Test mapping of severity levels."""
    assert spotbug_parser._map_severity("error") == AnalyticQSeverity.HIGH
    assert spotbug_parser._map_severity("warning") == AnalyticQSeverity.MEDIUM
    assert spotbug_parser._map_severity("note") == AnalyticQSeverity.LOW
    assert spotbug_parser._map_severity("info") == AnalyticQSeverity.INFO
    assert spotbug_parser._map_severity("unknown") == AnalyticQSeverity.UNKNOWN


def test_confidence_mapping(spotbug_parser):
    """Test mapping of confidence levels."""
    assert spotbug_parser._map_confidence("any") == AnalyticQConfidence.UNKNOWN


def test_get_field_with_dot_notation(spotbug_parser):
    """Test _get_field method with nested dot notation."""
    test_data = {
        "locations": [
            {
                "physicalLocation": {
                    "artifactLocation": {
                        "uri": "test.java"
                    }
                }
            }
        ]
    }

    value = spotbug_parser._get_field(test_data, "path")
    assert value == "test.java"

    # Test with non-existent path
    value = spotbug_parser._get_field(test_data, "nonexistent", "default")
    assert value == "default"

    # Test with partially existent path
    value = spotbug_parser._get_field(test_data, "start_line", 0)
    assert value == 0


def test_extract_rule_details(spotbug_parser, sample_sarif_data):
    """Test extraction of rule details."""
    rule_details = spotbug_parser._extract_rule_details(sample_sarif_data)

    assert "EI_EXPOSE_REP" in rule_details
    assert "DLS_DEAD_LOCAL_STORE" in rule_details

    assert rule_details["EI_EXPOSE_REP"]["description"] == "May expose internal representation by returning reference to mutable object"
    assert rule_details["EI_EXPOSE_REP"]["help_uri"] == "https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html#EI_EXPOSE_REP"
    assert "security" in rule_details["EI_EXPOSE_REP"]["tags"]


def test_extract_location_info(spotbug_parser, sample_sarif_data):
    """Test extraction of location information."""
    result = sample_sarif_data["runs"][0]["results"][0]

    location = spotbug_parser._extract_location_info(result)

    assert location["uri"] == "src/main/java/com/example/Data.java"
    assert location["startLine"] == 25
    assert location["endLine"] == 27


def test_transform_single_issue(spotbug_parser, sample_sarif_data):
    """Test transformation of a single issue."""
    rule_details = spotbug_parser._extract_rule_details(sample_sarif_data)
    result = sample_sarif_data["runs"][0]["results"][0]

    transformed = spotbug_parser._transform_single_issue(result, rule_details)

    assert transformed["ruleId"] == "EI_EXPOSE_REP"
    assert transformed["message"]["text"] == "This method returns a reference to an array that may be mutable"
    assert transformed["level"] == "error"
    assert transformed["locations"][0]["physicalLocation"]["artifactLocation"]["uri"] == "src/main/java/com/example/Data.java"
    assert transformed["locations"][0]["physicalLocation"]["region"]["startLine"] == 25
    assert transformed["locations"][0]["physicalLocation"]["region"]["endLine"] == 27
    assert transformed["metadata"]["rule_description"] == "May expose internal representation by returning reference to mutable object"


def test_empty_sarif(spotbug_parser):
    """Test handling of empty SARIF input."""
    empty_input = {"runs": [{"tool": {"driver": {"rules": []}}, "results": []}]}

    result = spotbug_parser.parse_scan_result(empty_input)
    assert len(result.issues) == 0
    assert result.summary["total"] == 0


@patch('analyticq.engine.core.AnalyticQResultParser.parse_scan_result')
def test_exception_handling(mock_parse, spotbug_parser, sample_sarif_data):
    """Test exception handling during parsing."""
    mock_parse.side_effect = KeyError("Test exception")

    with pytest.raises(ScanParserException) as excinfo:
        spotbug_parser.parse_scan_result(sample_sarif_data)

    assert "Unexpected error parsing SpotBugs SARIF results" in str(excinfo.value)
