env:
  SECRET_KEY: "test_env_secret_key"
  ANALYTICQ_CONFIG: '{"host": "localhost", "port": 8000}'

name: CI/CD for analyticq-backend

permissions:
  contents: read
  packages: write
  actions: read

on:
  push:
    branches:
      - dev

jobs:
    build-and-test:
        runs-on: ${{matrix.os}}
        strategy:
          matrix:
            os: [ubuntu-22.04, windows-latest]
            python-version: ["3.11", "3.12", "3.13"]
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python $${{matrix.python-version}}
          uses: actions/setup-python@v2
          with:
            python-version: ${{matrix.python-version}}

        - name: Cache Python dependencies
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: pip-${{ runner.os }}-${{ hashFiles('analyticq-backend/requirements.txt') }}
            restore-keys: |
              pip-${{ runner.os }}-

        - name: Install backend dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r analyticq-backend/requirements.txt --no-deps

        - name: Setup configuration files
          run: |
            echo "SECRET_KEY=test_env_secret_key" > analyticq-backend/config/.env.test
            echo '{"host": "localhost", "port": 8000}' > analyticq-backend/config/analyticq_backend_config.json
            cp analyticq-backend/tests/unit/test_files/.env.test.sample analyticq-backend/tests/unit/test_files/.env.test

        - name: Run Flake 8 linter on production code
          run: |
              pip install flake8
              flake8 analyticq-backend/analyticq

        - name: Run unit tests and code coverage generation report
          run: |
            python -m pip install pytest pytest-asyncio pytest-cov
            pytest analyticq-backend/tests/unit --cov=analyticq-backend --cov-report=xml:coverage.xml

        - name: Upload coverage report as artifact
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.run_number }}-${{ github.sha }}
            path: coverage.xml

        - name: Run SAST analysis backend with Bandit
          run: |
            python -m pip install bandit
            bandit -r analyticq-backend -x analyticq-backend/tests -o bandit-report.txt -f txt --exit-zero

        - name: Upload Bandit report as artifact
          uses: actions/upload-artifact@v4
          with:
            name: bandit-report-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.run_number }}-${{ github.sha }}
            path: bandit-report*.txt

    build-and-push:
        runs-on: ubuntu-22.04
        needs: build-and-test
        steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Log in to Docker hub
             uses: docker/login-action@v2
             with:
               username: ${{ github.actor}}
               password: ${{ secrets.GITHUB_TOKEN}}
               registry: ghcr.io

           - name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v2

           - name: Build and push backend Docker image
             run: |
                 docker buildx create --use
                 docker buildx build  \
                  --platform linux/amd64,linux/arm64 \
                  -t ghcr.io/${{ github.repository }}/analyticq-backend:${{ github.sha }} \
                  -t ghcr.io/${{ github.repository }}/analyticq-backend:latest \
                  -f ./analyticq-backend/Dockerfile ./analyticq-backend \
                  --push

           - name: Log out from Docker Hub
             run: docker logout ghcr.io
