name: CI/CD for pushing SAST tools Docker image

permissions:
  contents: read
  packages: write
  actions: read

on:
  push:
    branches:
      - dev

jobs:
  push-bandit:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: bandit
      dockerfile: ./sast-tools/python/bandit/Dockerfile
      context: ./sast-tools/python/bandit

  push-pylint:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: pylint
      dockerfile: ./sast-tools/python/pylint/Dockerfile
      context: ./sast-tools/python/pylint

  push-staticheck:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: staticcheck
      dockerfile: ./sast-tools/go/staticcheck/Dockerfile
      context: ./sast-tools/go/staticcheck

  push-flawfinder:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: flawfinder
      dockerfile: ./sast-tools/c/flawfinder/Dockerfile
      context: ./sast-tools/c/flawfinder

  push-spotbugs:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: spotbugs
      dockerfile: ./sast-tools/java/spotbugs/Dockerfile
      context: ./sast-tools/java/spotbugs

  push-phphstan:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: phpstan
      dockerfile: ./sast-tools/php/phpstan/Dockerfile
      context:  ./sast-tools/php/phpstan

  push-sqlfluff:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: sqlfluff
      dockerfile: ./sast-tools/sql/sqlfluff/Dockerfile
      context: ./sast-tools/sql/sqlfluff
