name: CI/CD for pushing SAST tools Docker image

permissions:
  contents: read
  packages: write
  actions: read


on:
  push:
    branches:
      - dev

jobs:
  push-bandit:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: bandit
      dockerfile: ./sast-tools/python/bandit/Dockerfile
      context: ./sast-tools/python/bandit
