name: CI/CD for pushing SAST tools Docker image

permissions:
  contents: read
  packages: write
  actions: read

on:
  push:
    branches:
      - dev

jobs:
  push-bandit:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: bandit
      dockerfile: ./sast-tools/python/bandit/Dockerfile
      context: ./sast-tools/python/bandit

  push-pylint:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: pylint
      dockerfile: ./sast-tools/python/pylint/Dockerfile
      context: ./sast-tools/python/pylint

  push-flake8:
     uses: ./.github/workflows/docker-build.yml
     with:
      image_name: flake8
      dockerfile: ./sast.tools/python/flake8/Dockerfile
      context: ./sast.tools/python/flake8

  push-staticheck:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: staticcheck
      dockerfile: ./sast-tools/go/staticcheck/Dockerfile
      context: ./sast-tools/go/staticcheck

  push-flawfinder:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: flawfinder
      dockerfile: ./sast-tools/c/flawfinder/Dockerfile
      context: ./sast-tools/c/flawfinder

  push-spotbugs:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: spotbugs
      dockerfile: ./sast-tools/java/spotbugs/Dockerfile
      context: ./sast-tools/java/spotbugs

  push-phphstan:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: phpstan
      dockerfile: ./sast-tools/php/phpstan/Dockerfile
      context:  ./sast-tools/php/phpstan

  push-cppcheck:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: cppcheck
      dockerfile: ./sast-tools/c/cppcheck/Dockerfile
      context: ./sast-tools/c/cppcheck

  push-rubocop:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: rubocop
      dockerfile: ./sast-tools/ruby/rubocop/Dockerfile
      context: ./sast-tools/ruby/rubocop

  push-eslint:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: eslint
      dockerfile: ./sast-tools/js/eslint/Dockerfile
      context: ./sast-tools/js/eslint
